config/routes.rb
CivicAppPetitionPrototype::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'petitions#index'
  
  resources :petitions do
    resources :responses, :shallow => true
  end
  
  resources :residents
  resources :politicians
  resources :users
  resources :constants
  
  # Constants
  #get "/constants/edit" => "constants#edit"
  #post "/constants/:id" => "constants#update"
  post "/contants/:id/update", :to => "constants#update"#, :as => :constants
  
  # Login
  get "/login" => "user_session#new"
  post "/login" => "user_session#create"
  get "/logout" => "user_session#destroy"
  
  # AdminController
  get "/admin" => "admin#index"
  
  post "/petitions/:id/sign" => "petitions#sign"
  
  get "/search" => "petitions#search"
  get "/petitions/search" => "petitions#search"
  
  get "/petitions/find/:query" => "petitions#find"
  
  # Report a petition
  post "/petitions/:id/report" => "petitions#report"
  
  # Generate live previews
  post "/preview" => "petitions#preview"
  
  
  # Paginate Petitions
  get "/petitions/page/:page" => "petitions#index"

  # Paginate signatures
  get "/petitions/:id/:page" => "petitions#show"
  
  # Paginate political responses
  get "/politicians/:id/:page" => "politicians#show"
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/constants.rb
class Constants < ActiveRecord::Base
  
  
  
end

app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :resident
  has_many :signatures, :dependent => :destroy
  has_many :responses, :dependent => :destroy
  has_many :reports, :dependent => :destroy
  
  before_create :setGoal
  after_create :signByOwner
  
  def self.approved
    select { |p| p.signatures.count >= p.goal }
  end
  
  def approved?
    self.signatures.count >= self.goal
  end

  private
  
  def setGoal
    #Set a default if nothing is set
    if self.goal.nil?
      goal = Constants.first.goal
      self.goal = goal
    end
  end
  
  def signByOwner
    Signature.create \
      :resident => self.resident,
      :petition => self
  end
  
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  has_many :responses
  
  has_one :user, :as => :role
  accepts_nested_attributes_for :user
  
  def addressed?(petition)
    self.responses.where(:petition => petition).exists?
  end
  
  def response_for(petition)
    self.responses.find_by :petition => petition
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :petition
  belongs_to :resident
  
  validates :resident, :uniqueness => { :scope => :petition }
end

app/models/resident.rb
class Resident < ActiveRecord::Base
  has_many :signatures
  has_many :petitions
  has_many :reports
  
  has_one :user, :as => :role
  accepts_nested_attributes_for :user
  
  def signed?(petition)
    self.signatures.where(:petition_id => petition.id).exists?
  end
  
  def reported?(petition)
    self.reports.where(:petition_id => petition.id).exists?
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :petition
  belongs_to :politician
  
  validates :statement, :presence => true

end

app/models/signature.rb
class Signature < ActiveRecord::Base
  belongs_to :petition
  belongs_to :resident
  
  validates :resident, :uniqueness => { :scope => :petition }
  
  # Set default for pagination
  self.per_page = 20
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :name#, :email, :password, :password_confirmation # Used for active admin purposes
  belongs_to :role, :polymorphic => true
  
  acts_as_authentic do |config|
    config.login_field = :email
  end
  
  def is_politician?
    self.role.is_a? Politician
  end
  
  def is_resident?
    self.role.is_a? Resident
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :ensure_admin
  
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    user = User.find(params[:id])
    redirect_to user.role
  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constants_helper.rb
module ConstantsHelper
end

app/helpers/petition_helper.rb
module PetitionHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/views/admin/index.html.erb
<div class="row">
  <!-- Actions -->
  <div class="col-md-4 col-sm-6">
    <ul class="list-unstyled">
      <li>TODO Manage Politicians</li>
      <li>TODO Manage Residents</li>
      <li><%= link_to "Configure System Values", constants_edit_path %></li>
    </ul>
  </div>
  
  <!-- Summary -->
  <div class="col-md-8 col-sm-6">
    TODO
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @constants.site_title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="civic">
  
  <%= render :partial => "partials/navigation" %>
  
  <%= content_for :top %>
  
  <div class="container">
    <% if flash[:error] %>
      <div class="alert alert-danger fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= flash[:error] %>
      </div>
    <% end %>
    
    <% if flash[:info] %>
        <div class="alert alert-info fade in">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <%= flash[:info] %>
        </div>
    <% end %>

    <% if flash[:success] %>
        <div class="alert alert-success fade in">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <%= flash[:success] %>
        </div>
    <% end %>

  	<%= yield %>
  </div>
  
  <!-- Fancy footer -->
  <div id="footer">
  	<div class="container">
    	<p class="text-muted">Everyday City People  v<%= @version %> &copy; BAA 2014</p>
    </div>
  </div>
</body>
</html>

app/views/partials/_big_banner.html.erb
<div class="jumbotron">
  <div class="container">
    <h1><%= @constants.site_title %></h1>
    <p><%= @constants.site_description %></p>
    <p>
      <% unless current_user && current_user.is_politician? %>
        <%= link_to "Create Petition", new_petition_path, :class => "btn btn-primary btn-lg" %>
        or 
      <% end %>
      
    	<%= link_to "Find a Petition", "/search", :class => "btn btn-success btn-lg" %>
  	</p>
  </div>
</div>

app/views/partials/_logged_in.html.erb
<div class="pull-right">
  <span class="navbar-text">
      Welcome, <%= link_to current_user.role.name, user_path(current_user), :class => "text-muted" %>

  </span>
  
  <%= link_to "Sign Out", logout_path, :class => "btn btn-default navbar-btn" %>  
</div>

app/views/partials/_login.html.erb
<%= form_for :user_session,
    :url => {
      :controller => "user_session",
      :action => :create
    },
    :html => {
      :class => "navbar-form navbar-right",
      :role => "form" } do |user| %>
  <div class="form-group">
    <%= user.email_field :email, :class => "form-control", :placeholder => "e-mail" %>
  </div>

  <div class="form-group">
    <%= user.password_field :password, :class => "form-control", :placeholder => "password" %>
  </div>
  
  <%= user.submit "Sign In", :class => "btn btn-success" %>
  
  <span data-no-turbolink>
    <%= link_to "Sign Up", new_resident_path, :class => "btn btn-primary" %>
  </span>
<% end %>

app/views/partials/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= @constants.site_title %></a>
    </div>
    <div class="navbar-collapse collapse">
      <% if current_user %>
        <%= render :partial => "partials/logged_in" %>
      <% else %>
        <%= render :partial => "partials/login" %>      
      <% end %>
    </div>
  </div>
</div>