config/routes.rb
CivicAppPetitionPrototype::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'petitions#index'
  
  resources :petitions do
    resources :responses, :shallow => true
  end
  
  resources :residents
  resources :politicians
  resources :users
  resources :constants
  
  # Constants
  #get "/constants/edit" => "constants#edit"
  #post "/constants/:id" => "constants#update"
  post "/contants/:id/update", :to => "constants#update"#, :as => :constants
  
  # Login
  get "/login" => "user_session#new"
  post "/login" => "user_session#create"
  get "/logout" => "user_session#destroy"
  
  # AdminController
  get "/admin" => "admin#index"
  
  post "/petitions/:id/sign" => "petitions#sign"
  
  get "/search" => "petitions#search"
  get "/petitions/search" => "petitions#search"
  
  get "/petitions/find/:query" => "petitions#find"
  
  # Report a petition
  post "/petitions/:id/report" => "petitions#report"
  
  # Generate live previews
  post "/preview" => "petitions#preview"
  
  
  # Paginate Petitions
  get "/petitions/page/:page" => "petitions#index"

  # Paginate signatures
  get "/petitions/:id/:page" => "petitions#show"
  
  # Paginate political responses
  get "/politicians/:id/:page" => "politicians#show"
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/constants.rb
class Constants < ActiveRecord::Base
  
  
  
end

app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :resident
  has_many :signatures, :dependent => :destroy
  has_many :responses, :dependent => :destroy
  has_many :reports, :dependent => :destroy
  
  before_create :setGoal
  after_create :signByOwner
  
  def self.approved
    select { |p| p.signatures.count >= p.goal }
  end
  
  def approved?
    self.signatures.count >= self.goal
  end

  private
  
  def setGoal
    #Set a default if nothing is set
    if self.goal.nil?
      goal = Constants.first.goal
      self.goal = goal
    end
  end
  
  def signByOwner
    Signature.create \
      :resident => self.resident,
      :petition => self
  end
  
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  has_many :responses
  
  has_one :user, :as => :role
  accepts_nested_attributes_for :user
  
  def addressed?(petition)
    self.responses.where(:petition => petition).exists?
  end
  
  def response_for(petition)
    self.responses.find_by :petition => petition
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :petition
  belongs_to :resident
  
  validates :resident, :uniqueness => { :scope => :petition }
end

app/models/resident.rb
class Resident < ActiveRecord::Base
  has_many :signatures
  has_many :petitions
  has_many :reports
  
  has_one :user, :as => :role
  accepts_nested_attributes_for :user
  
  def signed?(petition)
    self.signatures.where(:petition_id => petition.id).exists?
  end
  
  def reported?(petition)
    self.reports.where(:petition_id => petition.id).exists?
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :petition
  belongs_to :politician
  
  validates :statement, :presence => true

end

app/models/signature.rb
class Signature < ActiveRecord::Base
  belongs_to :petition
  belongs_to :resident
  
  validates :resident, :uniqueness => { :scope => :petition }
  
  # Set default for pagination
  self.per_page = 20
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :name#, :email, :password, :password_confirmation # Used for active admin purposes
  belongs_to :role, :polymorphic => true
  
  acts_as_authentic do |config|
    config.login_field = :email
  end
  
  def is_politician?
    self.role.is_a? Politician
  end
  
  def is_resident?
    self.role.is_a? Resident
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :ensure_admin
  
  def index
    
  end
end

app/controllers/constants_controller.rb
class ConstantsController < ApplicationController

  # TODO Make sure it comes from the admin dashboard
  def update
    @constants.update constant_params

    redirect_to admin_constants_url 
  end
  
  private
  
  def constant_params
    params.require(:constants).permit(:goal, :site_title, :site_description, :resident_intro)
  end
end

app/controllers/petition_controller.rb
class PetitionController < ApplicationController
  #
  def index
    @petitions=Petition.first
  end
  
  def new
    @petition=Petition.new
  end
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  def new
    @user = User.new
    @resident = Resident.new :user => @user
  end
  
  def show
    if @current_user.nil? then 
      redirect_to login_path
    end
    
    @user = Resident.find(params[:id])
  end
  
  def create
    @resident = Resident.new resident_params
    
    begin
      @resident.save!
      @resident.user.save!
      
      redirect_to resident_path @resident
    rescue Exception => e
      flash[:error] = e.to_s
      render :action => :new
    end
  end
  
  private
  
  def resident_params
    params.require(:resident).permit(:name, :user_attributes => [:email, :password, :password_confirmation])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    user = User.find(params[:id])
    redirect_to user.role
  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constants_helper.rb
module ConstantsHelper
end

app/helpers/petition_helper.rb
module PetitionHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/views/residents/new.html.erb
<%= form_for @resident,
    :html => {
      "ng-controller" => "ResidentFormController",
      :class => "form",
      :role => "form" } do |resident| %>
      
	<div class="form-group" ng-class="{ 'has-error': error.name }">
		<%= resident.label :name %>
    <%= resident.text_field :name,
      "ng-model" => "model.name",
      "ng-blur" => "updateError('name')",
      :class => "form-control" %>
    <p class="help-block text-error" ng-show="error.name">{{ error.name }}</p>
	</div>
	
	<%= resident.fields_for :user do |user| %>
		<div class="form-group" ng-class="{ 'has-error': error.email }">
			<%= user.label :email %>
      <%= user.text_field :email,
        "ng-model" => "model.email",
        "ng-blur" => "updateError('email')",
        :class => "form-control" %>
      <p class="help-block text-error" ng-show="error.email">{{ error.email }}</p>
		</div>
		
		<div class="form-group" ng-class="{ 'has-error': error.password }">
			<%= user.label :password %>
      <%= user.password_field :password,
        "ng-model" => "model.password",
        "ng-blur" => "updateError('password')",
        :class => "form-control" %>
      <p class="help-block text-error" ng-show="error.password">{{ error.password }}</p>
		</div>
		
		<div class="form-group" ng-class="{ 'has-error': error.password_confirmation }">
			<%= user.label :password_confirmation %>
      <%= user.password_field :password_confirmation,
        "ng-model" => "model.password_confirmation",
        "ng-blur" => "updateError('password_confirmation')",
        :class => "form-control" %>
      <p class="help-block text-error" ng-show="error.password_confirmation">{{ error.password_confirmation }}</p>
		</div>
		
	<% end %>
	
	<%= submit_tag "Sign Up", "ng-disabled" => "!allValid()", :class => "btn btn-success" %>
<% end %>

app/views/residents/show.html.erb
<div>
	
	<h2> Welcome, <%= @user.name %> </h2>
	<p><%= @constants.resident_intro %></p>
	<h2>My Petitions</h2>
	<% if @user.petitions.length == 0 %>
	<p>You haven't created any petitions yet, get started <%= link_to "here.", new_petition_path, :class => "btn btn-primary" %></p>
	<% else %>
	<ul>
		<% @user.petitions.each do |petition| %>
		
		<li><%= link_to petition.title, petition_path(petition) %></li>
		
		<% end %>
	</ul>
	<% end %>
	
</div>